-- public.state_appointment definition

-- Drop table

-- DROP TABLE public.state_appointment;

CREATE TABLE public.state_appointment (
                                          id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                          "uuid" uuid NOT NULL,
                                          created_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                          updated_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                          description varchar NOT NULL,
                                          state bool NOT NULL,
                                          CONSTRAINT state_appointment_pk PRIMARY KEY (id),
                                          CONSTRAINT state_appointment_unique UNIQUE (id)
);