-- public.age_group definition

-- Drop table

-- DROP TABLE public.age_group;

CREATE TABLE public.age_group (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"uuid" uuid NOT NULL,
	created_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	description varchar NOT NULL,
	state bool NOT NULL,
	CONSTRAINT age_group_pk PRIMARY KEY (id),
	CONSTRAINT age_group_unique UNIQUE (id)
);