-- public.doctor definition

-- Drop table

-- DROP TABLE public.doctor;

CREATE TABLE public.doctor (
                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               "uuid" uuid NOT NULL,
                               created_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               updated_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               speciality_id int8 NOT NULL,
                               state bool NOT NULL,
                               license varchar NOT NULL,
                               CONSTRAINT doctor_pk PRIMARY KEY (id),
                               CONSTRAINT doctor_unique UNIQUE (id),
                               CONSTRAINT doctor_speciality_fk FOREIGN KEY (speciality_id) REFERENCES public.speciality(id)
);