-- public.speciality definition

-- Drop table

-- DROP TABLE public.speciality;

CREATE TABLE public.speciality (
                                   id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                   "uuid" uuid NOT NULL,
                                   created_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                   updated_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                   description varchar NOT NULL,
                                   age_group_id int8 NOT NULL,
                                   sex bool NOT NULL,
                                   state bool NOT NULL,
                                   CONSTRAINT speciality_pk PRIMARY KEY (id),
                                   CONSTRAINT speciality_unique UNIQUE (id),
                                   CONSTRAINT speciality_age_group_fk FOREIGN KEY (age_group_id) REFERENCES public.age_group(id)
);