-- public.medical_appointment definition

-- Drop table

-- DROP TABLE public.medical_appointment;

CREATE TABLE public.medical_appointment (
                                            id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                            uuid uuid NOT NULL,
                                            created_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                            updated_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                            scheduled_for timestamp NOT NULL,
                                            reason varchar NOT NULL,
                                            state_appointment_id int8 NOT NULL,
                                            doctor_id int8 NOT NULL,
                                            Assistant varchar NOT NULL,
                                            state bool NOT NULL,
                                            CONSTRAINT medical_appointment_pk PRIMARY KEY (id),
                                            CONSTRAINT medical_appointment_unique UNIQUE (id),
                                            CONSTRAINT medical_appointment_doctor_fk FOREIGN KEY (doctor_id) REFERENCES public.doctor(id),
                                            CONSTRAINT medical_appointment_state_appointment_fk FOREIGN KEY (state_appointment_id) REFERENCES public.state_appointment(id)
);